# Generated by Django 4.1.7 on 2023-03-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_bookinstance_options_alter_language_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.CharField(help_text='Book description', max_length=300),
        ),
    ]
