# Generated by Django 4.1.7 on 2023-03-15 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_book_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='imprint',
        ),
    ]
