# Generated by Django 4.1.7 on 2023-03-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_bookinstance_imprint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='date_of_deasth',
            new_name='date_of_death',
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='due_back',
            field=models.DateField(blank=True, help_text='Когда будет возвращена если взята наруки', null=True, verbose_name='date'),
        ),
    ]
